server:
  port: 8080
  error:
    path: /error


spring:
  datasource:
    url: jdbc:postgresql://db.xyldjumtomiywpeucmmj.supabase.co:5432/postgres
    username: postgres
    password: vflk5eqXz1b5TlkH
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
