server:
  port: 8080
  error:
    path: /error


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
